name: CI Pipeline

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-write-only: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build code and test
        run: ./gradlew clean build
